name: Build macOS Executable

on:
  workflow_dispatch:   # Manual trigger only!

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed \
          --name "OVERCLOCK" \
          --icon "src/ui/assets/appicon.icns" \
          --add-data "src/ui/assets:src/ui/assets" \
          --hidden-import pyxirr \
          main.py

    - name: Upload built app bundle
      uses: actions/upload-artifact@v4
      with:
        name: overclock-macos-executable
        path: dist/OVERCLOCK.app 