name: Build Windows Executable

on:
  workflow_dispatch:   # Manual trigger only!

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'   

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "OVERCLOCK" --icon "src/ui/assets/appicon.ico" --add-data "src/ui/assets;src/ui/assets" --add-data "src/data;src/data" --hidden-import pyxirr main.py

    - name: Create zip with executable and readme
      run: |
        copy readme.txt dist\
        cd dist
        powershell Compress-Archive -Path "OVERCLOCK.exe", "readme.txt" -DestinationPath "overclock-windows.zip"

    - name: Upload built executable
      uses: actions/upload-artifact@v4
      with:
        name: overclock-windows-zip
        path: dist/overclock-windows.zip 