name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Download FFmpeg
      run: |
        Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -OutFile ffmpeg.zip
        Expand-Archive ffmpeg.zip -DestinationPath ffmpeg
        Rename-Item -Path (Get-ChildItem -Directory ffmpeg)[0].FullName -NewName ffmpeg-bin

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "OVERCLOCK" `
          --icon "src/ui/assets/appicon.ico" `
          --add-data "src/ui/assets;src/ui/assets" `
          --add-data "src/data;src/data" `
          --add-binary "ffmpeg-bin\\bin\\ffmpeg.exe;." `
          --add-binary "ffmpeg-bin\\bin\\ffprobe.exe;." `
          --hidden-import pyxirr `
          main.py

    - name: Create zip with executable and readme
      run: |
        copy readme.txt dist\
        copy ffmpeg-bin\bin\ffmpeg.exe dist\
        copy ffmpeg-bin\bin\ffprobe.exe dist\
        cd dist
        powershell Compress-Archive -Path "OVERCLOCK.exe", "readme.txt", "ffmpeg.exe", "ffprobe.exe" -DestinationPath "overclock-windows.zip"

    - name: Upload built executable
      uses: actions/upload-artifact@v4
      with:
        name: overclock-windows-zip
        path: dist/overclock-windows.zip